#pragma once

#define COUNT_MIN 1
#define SKIP_4_CHAR 4
#define SKIP_10_CHAR 10

#define SUCCESS 100
#define COUNT_LESS_THAN_MIN 101
#define NULL_SOLUTION 102
#define VALUE_LESS_THAN_MIN 103
#define VALUE_GREATER_THAN_MAX 104
#define FAILED_OPENING_FILE 105
#define INDEX_OUT_OF_RANGE 106
#define SOLUTION_COUNTS_NOT_EQ_PROBLEM_COUNTS 107
#define NULL_ARRAY 108
#define INCORRECT_ARRAY_LENGTH 109
#define NEGATIVE_CAPACITY 110
#define NEGATIVE_COST 111
#define NEGATIVE_REVENUE 112
#define NEGATIVE_VALUE 113