#pragma once

#define COUNT_MIN 1
#define SKIP_4_CHAR 4
#define SKIP_10_CHAR 10
#define DEFAULT_SEED 1

#define CAPS_MIN 39.7
#define CAPS_MAX 45.0

#define COSTS_MIN 2
#define COSTS_MAX 12

#define USE_COSTS_MIN 5
#define USE_COSTS_MAX 100

#define REVENUE_MIN 30
#define REVENUE_MAX 200

#define S_F_GOODS_MIN_MIN 10.0
#define S_F_GOODS_MIN_MAX 12.5
#define S_F_GOODS_MAX_MIN 15.0
#define S_F_GOODS_MAX_MAX 20.0

#define F_W_GOODS_MIN_MIN 7.5
#define F_W_GOODS_MIN_MAX 9.8
#define F_W_GOODS_MAX_MIN 10.0
#define F_W_GOODS_MAX_MAX 15.0

#define W_S_GOODS_MIN_MIN 1.2
#define W_S_GOODS_MIN_MAX 4.7
#define W_S_GOODS_MAX_MIN 5.0
#define W_S_GOODS_MAX_MAX 10.0

#define RANDOM_SEARCH_DEFAULT_COUNT 1000

//errors
#define SUCCESS 100
#define COUNT_LESS_THAN_MIN 101
#define NULL_SOLUTION 102
#define VALUE_LESS_THAN_MIN 103
#define VALUE_GREATER_THAN_MAX 104
#define FAILED_OPENING_FILE 105
#define INDEX_OUT_OF_RANGE 106
#define SOLUTION_COUNTS_NOT_EQ_PROBLEM_COUNTS 107
#define NULL_ARRAY 108
#define INCORRECT_ARRAY_LENGTH 109
#define NEGATIVE_CAPACITY 110
#define NEGATIVE_COST 111
#define NEGATIVE_REVENUE 112
#define NEGATIVE_VALUE 113
#define MAX_LESS_THAN_MIN 114
#define MIN_GREATER_THAN_MAX 115
#define COUNTS_NOT_SET 116